// <auto-generated />
using System;
using CKD.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CKD.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250428183830_AddTheProductPartsTableToTheDB_CKD04_DatabaseAsMappingBetweenProductsAndParts")]
    partial class AddTheProductPartsTableToTheDB_CKD04_DatabaseAsMappingBetweenProductsAndParts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CKD.DataAccess.Models.Part", b =>
                {
                    b.Property<string>("TechNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FarsiName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsSet")
                        .HasColumnType("bit");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("TechNo");

                    b.ToTable("TBL_Parts", (string)null);
                });

            modelBuilder.Entity("CKD.DataAccess.Models.Product", b =>
                {
                    b.Property<string>("ProductCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CreateByUserEID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EngineTypeDesc")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Notes2")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ProductVersion")
                        .HasColumnType("int");

                    b.HasKey("ProductCode");

                    b.ToTable("TBL_Products", (string)null);
                });

            modelBuilder.Entity("CKD.DataAccess.Models.ProductPart", b =>
                {
                    b.Property<string>("Product_ProductCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Part_TechNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.HasKey("Product_ProductCode", "Part_TechNo");

                    b.ToTable("TBL_ProductParts", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
